// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeGorevYonetimi.Data;

#nullable disable

namespace ProjeGorevYonetimi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424080519_AddSahaDenetimKapaliLog")]
    partial class AddSahaDenetimKapaliLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.AdetBirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdetBirimleri");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.CrossAppLoginToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CrossAppLoginTokens");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Durum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Durumlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<int?>("GorevGrubuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SorumluKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Turu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DurumId");

                    b.HasIndex("GorevGrubuId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("SorumluKullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GorevAtamalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevDurumLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DegistirenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EskiDurumId")
                        .HasColumnType("int");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<int>("YeniDurumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegistirenKullaniciId");

                    b.HasIndex("EskiDurumId");

                    b.HasIndex("GorevId");

                    b.HasIndex("YeniDurumId");

                    b.ToTable("GorevDurumLoglar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("GorevGruplar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("GorevYorumlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevYorumDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevYorumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevYorumId");

                    b.ToTable("GorevYorumDosyalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("CepTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CerezdenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SirketKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CerezdenKullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("IcerikHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NotGrupId")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotGrupId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotId");

                    b.ToTable("NotDosyalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("NotGruplar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotGrupYetkiKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("NotGrupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("NotGrupId");

                    b.ToTable("NotGrupYetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotYetkiKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("NotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("NotId");

                    b.ToTable("NotYetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlanlananBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjeDurumId")
                        .HasColumnType("int");

                    b.Property<int?>("SorumluKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("ProjeDurumId");

                    b.HasIndex("SorumluKullaniciId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Adet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AdetBirimiId")
                        .HasColumnType("int");

                    b.Property<string>("AdimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CikisFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaliyetFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int?>("SorumluKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdetBirimiId");

                    b.HasIndex("DurumId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("ProjeId");

                    b.HasIndex("SorumluKullaniciId");

                    b.ToTable("ProjeDetaylar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayDurumLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DegistirenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EskiDurumId")
                        .HasColumnType("int");

                    b.Property<int>("ProjeDetayId")
                        .HasColumnType("int");

                    b.Property<int>("YeniDurumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegistirenKullaniciId");

                    b.HasIndex("EskiDurumId");

                    b.HasIndex("ProjeDetayId");

                    b.HasIndex("YeniDurumId");

                    b.ToTable("ProjeDetayDurumLoglar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjeDetayKategoriler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjeDetayId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("ProjeDetayId");

                    b.ToTable("ProjeDetayYorumlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorumDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjeDetayYorumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjeDetayYorumId");

                    b.ToTable("ProjeDetayYorumDosyalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeSablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("ProjeSablonlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeSablonDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Adet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AdetBirimiId")
                        .HasColumnType("int");

                    b.Property<string>("AdimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("ProjeSablonId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdetBirimiId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("ProjeSablonId");

                    b.ToTable("ProjeSablonDetaylar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeYetkiKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeYetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("GeriAcanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeriAcmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("KapaliMi")
                        .HasColumnType("bit");

                    b.Property<int?>("KapatanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KapatmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeriAcanKullaniciId");

                    b.HasIndex("KapatanKullaniciId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("SahaDenetimler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Not")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelYorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("SahaDenetimId")
                        .HasColumnType("int");

                    b.Property<int?>("SahaDenetimKategoriId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("Tipler")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("YapildiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SahaDenetimId");

                    b.HasIndex("SahaDenetimKategoriId");

                    b.ToTable("SahaDenetimAdimlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdimIlgiliKisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SahaDenetimAdimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SahaDenetimAdimId");

                    b.ToTable("SahaDenetimAdimIlgiliKisiler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdimIlgiliUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Adet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SahaDenetimAdimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SahaDenetimAdimId");

                    b.ToTable("SahaDenetimAdimIlgiliUrunler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsertedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SahaDenetimKategoriler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Gorev", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "Durum")
                        .WithMany("Gorevler")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.GorevGrubu", "GorevGrubu")
                        .WithMany("Gorevler")
                        .HasForeignKey("GorevGrubuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturulanGorevler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "SorumluKullanici")
                        .WithMany()
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Durum");

                    b.Navigation("GorevGrubu");

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("SorumluKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevAtama", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Gorev", "Gorev")
                        .WithMany("Atamalar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany("GorevAtamalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevDurumLog", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "DegistirenKullanici")
                        .WithMany()
                        .HasForeignKey("DegistirenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "EskiDurum")
                        .WithMany()
                        .HasForeignKey("EskiDurumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "YeniDurum")
                        .WithMany()
                        .HasForeignKey("YeniDurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DegistirenKullanici");

                    b.Navigation("EskiDurum");

                    b.Navigation("Gorev");

                    b.Navigation("YeniDurum");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevGrubu", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevYorum", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Gorev", "Gorev")
                        .WithMany("Yorumlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevYorumDosya", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.GorevYorum", "GorevYorum")
                        .WithMany("Dosyalar")
                        .HasForeignKey("GorevYorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevYorum");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Not", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.NotGrup", "NotGrup")
                        .WithMany("Notlar")
                        .HasForeignKey("NotGrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotGrup");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotDosya", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Not", "Not")
                        .WithMany("Dosyalar")
                        .HasForeignKey("NotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Not");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotGrup", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotGrupYetkiKullanici", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.NotGrup", "NotGrup")
                        .WithMany("YetkiKullanicilar")
                        .HasForeignKey("NotGrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("NotGrup");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotYetkiKullanici", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Not", "Not")
                        .WithMany("YetkiKullanicilar")
                        .HasForeignKey("NotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Not");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Proje", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "ProjeDurum")
                        .WithMany("Projeler")
                        .HasForeignKey("ProjeDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "SorumluKullanici")
                        .WithMany("ProjelerSorumlu")
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("ProjeDurum");

                    b.Navigation("SorumluKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetay", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.AdetBirimi", "AdetBirimi")
                        .WithMany()
                        .HasForeignKey("AdetBirimiId");

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "Durum")
                        .WithMany("ProjeDetaylar")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeDetayKategori", "Kategori")
                        .WithMany("ProjeDetaylar")
                        .HasForeignKey("KategoriId");

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Proje", "Proje")
                        .WithMany("Detaylar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "SorumluKullanici")
                        .WithMany("ProjeDetaylarSorumlu")
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdetBirimi");

                    b.Navigation("Durum");

                    b.Navigation("Kategori");

                    b.Navigation("Proje");

                    b.Navigation("SorumluKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayDurumLog", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "DegistirenKullanici")
                        .WithMany()
                        .HasForeignKey("DegistirenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "EskiDurum")
                        .WithMany()
                        .HasForeignKey("EskiDurumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeDetay", "ProjeDetay")
                        .WithMany()
                        .HasForeignKey("ProjeDetayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Durum", "YeniDurum")
                        .WithMany()
                        .HasForeignKey("YeniDurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DegistirenKullanici");

                    b.Navigation("EskiDurum");

                    b.Navigation("ProjeDetay");

                    b.Navigation("YeniDurum");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorum", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "InsertedByUser")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeDetay", "ProjeDetay")
                        .WithMany("Yorumlar")
                        .HasForeignKey("ProjeDetayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsertedByUser");

                    b.Navigation("ProjeDetay");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorumDosya", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorum", "ProjeDetayYorum")
                        .WithMany("Dosyalar")
                        .HasForeignKey("ProjeDetayYorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjeDetayYorum");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeSablon", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeSablonDetay", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.AdetBirimi", "AdetBirimi")
                        .WithMany()
                        .HasForeignKey("AdetBirimiId");

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeDetayKategori", "Kategori")
                        .WithMany("SablonDetaylar")
                        .HasForeignKey("KategoriId");

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.ProjeSablon", "ProjeSablon")
                        .WithMany("Detaylar")
                        .HasForeignKey("ProjeSablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdetBirimi");

                    b.Navigation("Kategori");

                    b.Navigation("ProjeSablon");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeYetkiKullanici", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Proje", "Proje")
                        .WithMany("YetkiKullanicilar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetim", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "GeriAcanKullanici")
                        .WithMany()
                        .HasForeignKey("GeriAcanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "KapatanKullanici")
                        .WithMany()
                        .HasForeignKey("KapatanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeriAcanKullanici");

                    b.Navigation("KapatanKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdim", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.SahaDenetim", "SahaDenetim")
                        .WithMany("Adimlar")
                        .HasForeignKey("SahaDenetimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeGorevYonetimi.Models.Entities.SahaDenetimKategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("SahaDenetimKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kategori");

                    b.Navigation("SahaDenetim");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdimIlgiliKisi", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdim", "SahaDenetimAdim")
                        .WithMany("IlgiliKisiler")
                        .HasForeignKey("SahaDenetimAdimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SahaDenetimAdim");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdimIlgiliUrun", b =>
                {
                    b.HasOne("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdim", "SahaDenetimAdim")
                        .WithMany("IlgiliUrunler")
                        .HasForeignKey("SahaDenetimAdimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SahaDenetimAdim");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Durum", b =>
                {
                    b.Navigation("Gorevler");

                    b.Navigation("ProjeDetaylar");

                    b.Navigation("Projeler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Gorev", b =>
                {
                    b.Navigation("Atamalar");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevGrubu", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.GorevYorum", b =>
                {
                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("GorevAtamalari");

                    b.Navigation("OlusturulanGorevler");

                    b.Navigation("ProjeDetaylarSorumlu");

                    b.Navigation("ProjelerSorumlu");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Not", b =>
                {
                    b.Navigation("Dosyalar");

                    b.Navigation("YetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.NotGrup", b =>
                {
                    b.Navigation("Notlar");

                    b.Navigation("YetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.Proje", b =>
                {
                    b.Navigation("Detaylar");

                    b.Navigation("YetkiKullanicilar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetay", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayKategori", b =>
                {
                    b.Navigation("ProjeDetaylar");

                    b.Navigation("SablonDetaylar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeDetayYorum", b =>
                {
                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.ProjeSablon", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetim", b =>
                {
                    b.Navigation("Adimlar");
                });

            modelBuilder.Entity("ProjeGorevYonetimi.Models.Entities.SahaDenetimAdim", b =>
                {
                    b.Navigation("IlgiliKisiler");

                    b.Navigation("IlgiliUrunler");
                });
#pragma warning restore 612, 618
        }
    }
}
